// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbrQd2s5OwZx6RL9LFefLJk-L0xe7kZSw',
    appId: '1:165656076508:web:8bcf2d8bc3a34c442b5419',
    messagingSenderId: '165656076508',
    projectId: 'mbari-b7bb4',
    authDomain: 'mbari-b7bb4.firebaseapp.com',
    storageBucket: 'mbari-b7bb4.firebasestorage.app',
    measurementId: 'G-WEWGRH2579',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP3wbnQ4Co4HQCCa8QRumumL0v52nbnFw',
    appId: '1:165656076508:android:2457ee8a83d601932b5419',
    messagingSenderId: '165656076508',
    projectId: 'mbari-b7bb4',
    storageBucket: 'mbari-b7bb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBipABZeGjV7HfEy_apWFeeFv7Bt2EdIDc',
    appId: '1:165656076508:ios:ff3db6774dacc6da2b5419',
    messagingSenderId: '165656076508',
    projectId: 'mbari-b7bb4',
    storageBucket: 'mbari-b7bb4.firebasestorage.app',
    iosBundleId: 'com.example.mbari',
  );
}
